# Generated by Django 3.1.12 on 2021-10-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210930_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ratingWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
